=== debabratahazra/EclipsePluginsProjectRepo/DS/designstudio/components/pageflow/tests/com.odcgroup.pageflow.generation.tests/resources/schema/pageflow/wui-workflow.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="http://www.odcgroup.com/wui-workflow" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.odcgroup.com/wui-workflow" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:annotation>
		<xs:documentation>Description of graphs and workflows for the WUI</xs:documentation>
	</xs:annotation>
	<xs:complexType name="Graph">
		<xs:annotation>
			<xs:documentation>Description of a flow as a state machine</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="state" type="State" minOccurs="2" maxOccurs="unbounded"/>
			<xs:element name="init-transition" type="Transition">
				<xs:annotation>
					<xs:documentation>First transition of the graph requiring no origin state</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="transition" maxOccurs="unbounded">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="Transition">
							<xs:attribute name="from-state" type="xs:IDREF" use="required"/>
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="name" type="xs:ID" use="required"/>
	</xs:complexType>
	<xs:complexType name="State">
		<xs:annotation>
			<xs:documentation>State of the workflow</xs:documentation>
		</xs:annotation>
		<xs:attribute name="key" type="xs:ID" use="required"/>
		<xs:attribute name="desc" type="xs:string" use="optional"/>
		<xs:attribute name="is-terminal" type="xs:boolean" use="optional" default="false"/>
	</xs:complexType>
	<xs:complexType name="Transition">
		<xs:annotation>
			<xs:documentation>Transtion from one state to either another state or a redirector</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element name="process" type="Process" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="validation" type="ValidationProcess" minOccurs="0" maxOccurs="unbounded"/>
			</xs:choice>
			<xs:element name="redirector" type="Redirector" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:NMTOKEN" use="required"/>
		<xs:attribute name="to-state" type="xs:IDREF" use="optional"/>
		<xs:attribute name="to-redirector" type="xs:boolean" use="optional" default="false"/>
		<xs:attribute name="is-idempotent" type="xs:boolean" use="optional" default="true"/>
	</xs:complexType>
	<xs:complexType name="Process">
		<xs:annotation>
			<xs:documentation>Process executing business logic (a Java class)</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="property" type="Property" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="class-name" type="xs:string" use="required"/>
		<xs:attribute name="stop-on-failure" type="xs:boolean" use="optional" default="true"/>
	</xs:complexType>
	<xs:complexType name="ValidationProcess">
		<xs:annotation>
			<xs:documentation>A Validation Process</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="property" type="Property" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="class-name" type="xs:string" use="optional" default="com.odcgroup.uif.validation.FormValidationProcess"/>
	</xs:complexType>
	<xs:complexType name="Redirector">
		<xs:annotation>
			<xs:documentation>Allows redirection to different states at the end of a transition</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="result" type="StateResult" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="StateResult">
		<xs:annotation>
			<xs:documentation>Association of a process result and a state</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="transition" type="Transition" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="value" type="xs:int" use="required"/>
		<xs:attribute name="state" type="xs:string" use="optional"/>
	</xs:complexType>
	<xs:complexType name="Workflow">
		<xs:annotation>
			<xs:documentation>Workflow described either with XML or a Java class</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="property" type="Property" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="abort-view" type="View">
				<xs:annotation>
					<xs:documentation>Displayed view in case of cancellation of the flow</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="error-view" type="View">
				<xs:annotation>
					<xs:documentation>Displayed view in case of error during the flow</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:choice maxOccurs="unbounded">
				<xs:element name="view" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="View">
								<xs:attribute name="state-key" type="xs:string" use="required"/>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="pageflow-view" type="PageflowView" minOccurs="0" maxOccurs="unbounded"/>
			</xs:choice>
		</xs:sequence>
		<xs:attribute name="name" type="xs:ID" use="required"/>
		<xs:attribute name="graph" type="xs:IDREF" use="optional"/>
		<xs:attribute name="graph-class-name" type="xs:string" use="optional"/>
	</xs:complexType>
	<xs:complexType name="Wizard">
		<xs:annotation>
			<xs:documentation>Wizard described either with XML or a Java class</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="view" maxOccurs="unbounded">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="View">
							<xs:attribute name="state-key" type="xs:string" use="required"/>
							<xs:attribute name="index" type="xs:int" use="required"/>
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="name" type="xs:ID" use="required"/>
		<xs:attribute name="workflow" type="xs:IDREF" use="optional"/>
	</xs:complexType>
	<xs:complexType name="View">
		<xs:annotation>
			<xs:documentation>On-screen representation of a state</xs:documentation>
		</xs:annotation>
		<xs:attribute name="url-redirector-class-name" type="xs:string" use="optional"/>
		<xs:attribute name="url" type="xs:anyURI" use="optional"/>
	</xs:complexType>
	<xs:complexType name="PageflowView">
		<xs:annotation>
			<xs:documentation>Association of a state to a nested pageflow</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="input-handler" type="Process" minOccurs="0"/>
			<xs:element name="output-handler" type="Process" minOccurs="0"/>
			<xs:element name="exit-transition" type="ExitTransition" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="state-key" type="xs:string" use="required"/>
		<xs:attribute name="configuration" type="xs:string" use="optional"/>
		<xs:attribute name="pageflow" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="ExitTransition">
		<xs:annotation>
			<xs:documentation>Defines the transition that will replace a terminal state of a nested pageflow</xs:documentation>
		</xs:annotation>
		<xs:attribute name="state" type="xs:string" use="required"/>
		<xs:attribute name="transition" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="Property">
		<xs:annotation>
			<xs:documentation>Property to be transferred to a Process</xs:documentation>
		</xs:annotation>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="value" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:element name="config">
		<xs:annotation>
			<xs:documentation>Root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element name="graph" type="Graph" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="workflow" type="Workflow" maxOccurs="unbounded"/>
				<xs:element name="wizard" type="Wizard" maxOccurs="unbounded"/>
			</xs:choice>
			<xs:attribute name="use-cache" type="xs:boolean" use="optional" default="true"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== debabratahazra/EclipsePluginsProjectRepo/DS/designstudio/components/pageflow/tests/com.odcgroup.pageflow.generation.tests/src/test/resources/com/odcgroup/pageflow/generation/tests/ds7899-pageflow-DS7899.xml
<?xml version="1.0" encoding="UTF-8"?>
	<wf:config xmlns:wf="http://www.odcgroup.com/wui-workflow" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.odcgroup.com/wui-workflow wui-workflow.xsd">
	<!-- 
		*************************************************************************************
																DO NOT MODIFY THIS FILE!

		This file has been generated automatically by Design Studio. 
		Any change will be lost when regenerated.
		*************************************************************************************
										Design Studio information of  pageflow file
										
		Project name     : pms-models
		Package          : //ds7899
		Generation user  : atripod
		Generation date  : Tue Sep 30 17:12:39 CEST 2014
		DS version       :  
		*************************************************************************************
	 -->
	
		
	<!-- 
		*****************************************************
		Design Studio information of pageflow model
		Model name       : DS7899
		Description      : 
		******************************************************
    -->	
    
	<!-- 
		*************************************
		DS7899 workflow
		*************************************
    -->

	<wf:workflow name="DS7899" graph="DS7899Graph">
	    <!-- declaration of the used panels -->
		<wf:abort-view url-redirector-class-name="com.odcgroup.uif.workflow.ConfigurableURLRedirector"/>
		<wf:error-view url="/page/common/OneModule?module=general/PageflowErrorModule"/>
		<wf:view state-key="EndState" url="exit"/>
	</wf:workflow>

	    
	<!--
		*************************************
		DS7899 graph
		*************************************
	-->
	
	<wf:graph name="DS7899Graph">
		<!-- ============================== -->	
	    <!-- declaration of the used states -->
	    <!-- ============================== -->
	    <wf:state key="EndState" is-terminal="true"/>
	    <wf:state key="ViewState"/>
   
    	<!-- ============================== -->
        <!-- declaration of init transition -->
        <!-- ============================== -->
        <wf:init-transition name="transition1" to-state="ViewState">        
	      	<wf:process class-name="com.odcgroup.tsl.core.wui.flow.CheckScreenProfileFlowService" stop-on-failure="false"/>
        </wf:init-transition>
        <!-- ============================== -->
        <!-- declaration of the transitions -->
        <!-- ============================== -->
        <wf:transition name="A" from-state="ViewState" to-redirector="true" >        
	      	<wf:process class-name="com.odcgroup.tsl.core.wui.flow.CheckScreenProfileFlowService" stop-on-failure="false"/>
  			<wf:process class-name="com.odcgroup.tsl.core.wui.process.RedirectorOnAttributeProcess"/>
			<wf:redirector>
 				<wf:result value="0">
 					<wf:transition to-state="ViewState" name="0" >
					      	<wf:process class-name="com.odcgroup.tsl.core.wui.flow.CheckScreenProfileFlowService" stop-on-failure="false"/>
 					</wf:transition>
 				</wf:result>
   				<wf:result state="ViewState" value="1" />
			</wf:redirector>
        </wf:transition>
        <wf:transition name="transition2" from-state="ViewState" to-state="EndState" >
	      	<wf:process class-name="com.odcgroup.tsl.core.wui.flow.CheckScreenProfileFlowService" stop-on-failure="false"/>
        </wf:transition>
	</wf:graph>


	</wf:config>
