=== debabratahazra/EclipsePluginsProjectRepo/DS/designstudio/components/t24/core/com.odcgroup.t24.application.model/src/main/resources/meta-t24.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--Schema initially automatically written by Odyssey Design Studio Schema generator from t24-meta.domain by Michael & Sathya. 
	Later simplified / cleaned-up and future maintenance by hand -->
<xs:schema targetNamespace="http://www.temenos.com/t24-meta"
    elementFormDefault="qualified" attributeFormDefault="unqualified"
    xmlns="http://www.temenos.com/t24-meta" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:complexType name="ApplicationReference">
        <xs:sequence>
            <xs:element name="component" type="xs:string"/>
            <xs:element name="module" type="xs:string"/>
            <xs:element name="name" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="ApplicationEntity">
        <xs:sequence>
        	<xs:element name="additional-info" type="xs:string"
        		minOccurs="0" />
        	<xs:element name="allowed-functions"
        		type="ApplicationFunction" minOccurs="0">
        		<xs:annotation>
        			<xs:documentation xml:lang="en">
        				TODO This property must be 0:n multi value! Or
        				use comma separation convention.. :-(
        			</xs:documentation>
        		</xs:annotation>
        	</xs:element>
        	<xs:element name="documentation" type="xs:string"
        		minOccurs="0">
        		<xs:annotation>
        			<xs:documentation xml:lang="en">
        				Long Helptext
        			</xs:documentation>
        		</xs:annotation>
        	</xs:element>
        	<xs:element name="fields" type="ApplicationField"
        		minOccurs="0" maxOccurs="unbounded" />
        	<xs:element name="header1" type="Translation" minOccurs="0"
        		maxOccurs="unbounded">
        	</xs:element>
        	<xs:element name="header2" type="Translation" minOccurs="0" maxOccurs="unbounded"></xs:element>
        	<xs:element name="level" type="ApplicationLevel" />
        	<xs:element name="long-description" type="xs:string"
        		minOccurs="0">
        		<xs:annotation>
        			<xs:documentation xml:lang="en">
        				Longer description, meaningful to business (this
        				is the DESCRITION from PGM File).
        			</xs:documentation>
        		</xs:annotation>
        	</xs:element>
        	<xs:element name="non-stop" type="xs:boolean" />
        	<xs:element name="short-description" type="xs:string"
        		minOccurs="0">
        		<xs:annotation>
        			<xs:documentation xml:lang="en">
        				One line label, meaningful to business (this is
        				the SCREEN_TITLE from PGM File).
        			</xs:documentation>
        		</xs:annotation>
        	</xs:element>
        	<xs:element name="type" type="ApplicationType"
        		minOccurs="0" /><!-- TODO minOccurs="0" is only temporary, until fixed XML is available -->
        	<xs:element name="version-control" type="xs:string"
        		minOccurs="0" />
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="name-t24" type="xs:string" use="optional" />
    </xs:complexType>
    <xs:complexType name="Component">
        <xs:sequence>
            <xs:element name="applications" type="ApplicationEntity"
                minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="documentation" type="xs:string" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>
    <xs:complexType name="DomainServiceRequest">
        <xs:sequence>
            <xs:element name="application-name-filter" type="xs:string" minOccurs="0"/>
            <xs:element name="component-name-filter" type="xs:string" minOccurs="0"/>
            <xs:element name="module-name-filter" type="xs:string" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="DomainServiceResponse">
        <xs:sequence>
            <xs:element name="modules" type="Module" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="t24-release" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="ApplicationField">
        <xs:sequence>
        	<xs:element name="alignment" type="FieldAlignment"
        		minOccurs="0" />
        	<xs:element name="business-type" type="xs:string"
        		minOccurs="0" />
        	<xs:element name="concat-file" type="xs:string"
        		minOccurs="0" />
        	<xs:element name="core" type="xs:boolean" />
        	<xs:element name="gen-operation" type="xs:string" minOccurs="0" />
        	<xs:element name="documentation" type="xs:string" 
        		minOccurs="0">
        		<xs:annotation>
        			<xs:documentation xml:lang="en">
        				Long Helptext
        			</xs:documentation>
        		</xs:annotation>
        	</xs:element>
        	<xs:element name="input-behaviour" type="InputBehaviour" />
            <xs:element name="is-image" type="xs:boolean" minOccurs="0" />
            <xs:element name="is-textarea" type="xs:boolean" minOccurs="0" />
            <xs:element name="onchange-behaviour" type="xs:string" minOccurs="0" />
            <xs:element name="label" type="Translation" minOccurs="0"
        		maxOccurs="unbounded">
        	</xs:element>
        	<xs:element name="mandatory" type="xs:boolean"
        		minOccurs="0" />
            <xs:element name="mask" type="xs:string" minOccurs="0" />
            <xs:element name="max-length" type="xs:integer"
        		minOccurs="0" />
        	<xs:element name="multi-language" type="xs:boolean"
        		minOccurs="0" />
        	<xs:element name="multi-value-group-name" type="xs:string"
        		minOccurs="0">
        		<xs:annotation>
        			<xs:documentation xml:lang="en">
        				typically the name of another Field in the same
        				Application, with a &amp;quot;grp*&amp;quot;
        				prefix?
        			</xs:documentation>
        		</xs:annotation>
        	</xs:element>
            <xs:element name="mv-sv-expansion-access" type="MvSvExpansionAccess" minOccurs="0" />
            <xs:element name="name-t24" type="xs:string" minOccurs="0" />
        	<xs:element name="primary-key" type="xs:boolean"
        		minOccurs="0">
        		<xs:annotation>
        			<xs:documentation xml:lang="en">
        				only one Field of an Application can have
        				primaryKey = true
        			</xs:documentation>
        		</xs:annotation>
        	</xs:element>
        	<xs:element name="range" type="xs:string" minOccurs="0" />
        	<xs:element name="ref-application"
        		type="ApplicationReference" minOccurs="0" />
        	<xs:element name="sub-value-group-name" type="xs:string"
        		minOccurs="0">
        		<xs:annotation>
        			<xs:documentation xml:lang="en">
        				if subValueGroupName is set, then
        				multiValueGroupName
        			</xs:documentation>
        		</xs:annotation>
        	</xs:element>
        	<xs:element name="sys-number" type="xs:double"
        		minOccurs="0" />
        	<xs:element name="tooltip" type="Translation" minOccurs="0" maxOccurs="unbounded"></xs:element>
        	<xs:element name="type" type="FieldType" minOccurs="0" />
            <xs:element name="type-modifiers" type="xs:string" minOccurs="0" />
            <xs:element name="valid-value" type="FieldValidValue" 
        		minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>
<!--    
    <xs:complexType name="BusinessType">
        <xs:sequence>
            <xs:element name="documentation" type="xs:string" minOccurs="0"/>
            <xs:element name="field-type" type="FieldType" minOccurs="0"/>
            <xs:element name="in2-routine-name" type="xs:string">
                <xs:annotation>
                    <xs:documentation xml:lang="en">This is the T24 IN2 Routine Name...

TODO: Make it multiplicity many</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="maximum-characters" type="xs:integer" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>
    <xs:complexType name="BusinessTypeServiceResponse">
        <xs:sequence>
            <xs:element name="all-business-types" type="BusinessType"
                minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="t24-release" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
 -->    
    <xs:complexType name="Translation">
        <xs:sequence>
            <xs:element name="locale" type="xs:string"/>
            <xs:element name="translation" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Module">
        <xs:sequence>
            <xs:element name="components" type="Component" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="documentation" type="xs:string" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>
    <xs:complexType name="FieldValidValue">
        <xs:sequence>
            <xs:element name="value" type="xs:string" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="FieldType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="S"/>
            <xs:enumeration value="B"/>
            <xs:enumeration value="N">
                <xs:annotation>
                    <xs:documentation xml:lang="en">AKA Float</xs:documentation>
                </xs:annotation>
            </xs:enumeration>
            <xs:enumeration value="D"/>
            <xs:enumeration value="L"/>
            <xs:enumeration value="C"/>
            <xs:enumeration value="T"/>
            <xs:enumeration value="M"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="ApplicationType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="H"/>
            <xs:enumeration value="U"/>
            <xs:enumeration value="L"/>
            <xs:enumeration value="D"/>
            <xs:enumeration value="W"/>
            <xs:enumeration value="T"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="ApplicationLevel">
        <xs:restriction base="xs:string">
            <xs:enumeration value="I"/>
            <xs:enumeration value="F"/>
            <xs:enumeration value="C"/>
            <xs:enumeration value="B"/>
            <xs:enumeration value="Y"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="InputBehaviour">
        <xs:restriction base="xs:string">
            <xs:enumeration value="I"/>
            <xs:enumeration value="N"/>
            <xs:enumeration value="F"/>
            <xs:enumeration value="E"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="FieldAlignment">
        <xs:restriction base="xs:string">
            <xs:enumeration value="R"/>
            <xs:enumeration value="L"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="ApplicationFunction">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
    <xs:simpleType name="MvSvExpansionAccess">
    	<xs:restriction base="xs:string">
    		<xs:enumeration value="NODELETE"></xs:enumeration>
    		<xs:enumeration value="NOEXPAND"></xs:enumeration>
    		<xs:enumeration value="NOMODIFY"></xs:enumeration>
    	</xs:restriction>
    </xs:simpleType>
    <xs:element name="meta-t24">
        <xs:complexType>
            <xs:choice>
                <xs:sequence minOccurs="0" maxOccurs="unbounded">
                    <xs:element name="domain-service-response"
                        type="DomainServiceResponse" minOccurs="0" maxOccurs="unbounded"/>
                </xs:sequence>
            </xs:choice>
             <!-- TODO remove this! -->
            <xs:attribute name="mode" use="optional" default="publish">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="publish"/>
                        <xs:enumeration value="remove"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== debabratahazra/EclipsePluginsProjectRepo/DS/designstudio/components/t24/tests/com.odcgroup.t24.application.importer.tests/resources/empty-valid-value.xml
<?xml version="1.0" encoding="UTF-8"?>
<t24:meta-t24 mode="publish" xmlns:t24="http://www.temenos.com/t24-meta"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.temenos.com/t24-meta ../../t24-meta-models-gen/src/impl/domain/META-INF/schemas/meta-t24.xsd">

	<t24:domain-service-response>
		<t24:modules name="FT1">
			<t24:components name="Contract">
				<t24:applications name="FUNDS.TRANSFER">
					<t24:allowed-functions>IARDS</t24:allowed-functions>
					<t24:documentation>Main Table Associated with Funds Transfer
					</t24:documentation>
					<t24:fields name="CUSTOMER_ID">
						<t24:alignment>L</t24:alignment>
						<t24:concat-file>LMM.CUSTOMER</t24:concat-file>
						<t24:core>true</t24:core>
						<t24:documentation>TO DO</t24:documentation>
						<t24:input-behaviour>F</t24:input-behaviour>
						<t24:mandatory>true</t24:mandatory>
						<t24:max-length>10</t24:max-length>
						<t24:multi-language>false</t24:multi-language>
						<t24:name-t24>CUSTOMER.ID</t24:name-t24>
						<t24:primary-key>false</t24:primary-key>
						<t24:sys-number>1</t24:sys-number>
						<t24:type>S</t24:type>
						<t24:valid-value>
						<t24:value>1 RATE CHANGE</t24:value>
						</t24:valid-value>
						<t24:valid-value>
						</t24:valid-value>
					</t24:fields>
                    <t24:level>F</t24:level>
					<t24:non-stop>true</t24:non-stop>
					<t24:type>H</t24:type>
				</t24:applications>
			</t24:components>
		</t24:modules>
		<t24:t24-release>123</t24:t24-release>
	</t24:domain-service-response>
</t24:meta-t24>
